### PR TITLE
Apostrophe encoding bugfix

### PR DESCRIPTION
**Pull request by lizzij**
- all special characters in professor names were rendered in HTML entity number (e.g., `'` is rendered as `&#39;`.
- used `unescape` from underscore.js to fix the bug.

### CODE REVIEW

**Comment by lizzij** [comment]
Closing this PR because the scope is encompassed in another ticket.

**Comment by zefwang** [comment]
LGTM

**Review by gamburgm — COMMENTED** [review]
I believe there are course titles that also have escaped characters in their names, going to see if I can find an example before we merge this

**Review by gamburgm — APPROVED** [review]
Good to go!

**Pull request merged**
