### PR TITLE
Remove Mailchimp

### PR DESCRIPTION
**Pull request by NEUDitao**
Mailchimp keeps causing server crashes and isn't used anymore -- let's remove it!

### CODE REVIEW

**Comment by NEUDitao** [comment]
I seem to be failing tests on my side due to ES -- can someone more knowledgeable than that take a look?

**Comment by dajinchu** [comment]
Are we sure this fixes the issues we were having? Its good either way to get rid of dead code, but I thought the errors were more FB related. Idk though, haven't had a chance to take a deep dive yet

**Comment by NEUDitao** [comment]
This won't fix the messenger bugs we've been having, but the server crash at 2:12 PM EDT yesterday was caused by a Mailchimp line. The messenger bugs are probably something to do with the fact that it's using an actual DB instead of a test one.

**Review by dajinchu — APPROVED** [review]
love to see code deletions :)

**Pull request merged**
